import pandas as pd
dataframe=pd.read_csv("myFile.csv")
print(dataframe)
print("==========================")
print("All elements in Usernames column:")
print(dataframe["Usernames"])
print("==========================")
print("Username in row 2:"+dataframe["Usernames"][1])
print("==========================")
print("Password in row 2:"+dataframe["Passwords"][1])
print("==========================")
print("Sorted in ascending order of usernames: ")
print(dataframe.sort_values("Usernames"))
print("==========================")
print("Sorted in ascending order of passwords: ")
print(dataframe.sort_values("Passwords"))
print("==========================")